// packages/ui-shared-solid/src/AccountSwitcher.tsx
/**
 * AccountSwitcher — Solid component for selecting the active Anthropic account.
 *
 * Always renders a <select> dropdown when at least one anthropic-kind account
 * is available. The leading "— Auto —" option (value="") lets the user revert
 * to broker rotation (null selectedAccountId). Unhealthy accounts are shown
 * as disabled options so the user can see they exist but cannot select them.
 */
import { type Component, For } from "solid-js"

export interface AccountSummary {
  readonly id: string
  readonly label: string
  readonly kind: string
  readonly health: string
}

export interface AccountSwitcherProps {
  readonly accounts: ReadonlyArray<AccountSummary>
  readonly selectedId: string | null
  readonly onSelect: (accountId: string | null) => void
  readonly disabled?: boolean
}

export const AccountSwitcher: Component<AccountSwitcherProps> = (props) => {
  const anthropicAccounts = () =>
    props.accounts.filter((a) => a.kind === "anthropic")

  // Don't render until we have account info from the server.
  if (anthropicAccounts().length === 0) return null

  return (
    <select
      value={props.selectedId ?? ""}
      disabled={props.disabled}
      onChange={(e) => {
        const val = e.currentTarget.value
        props.onSelect(val === "" ? null : val)
      }}
      style={{ "font-size": "inherit" }}
    >
      <option value="">— Auto —</option>
      <For each={anthropicAccounts()}>
        {(acct) => (
          <option
            value={acct.id}
            disabled={acct.health !== "healthy"}
          >
            {acct.label}
            {acct.health !== "healthy" ? " (unavailable)" : ""}
          </option>
        )}
      </For>
    </select>
  )
}

// apps/ui-web/src/studio/account-switcher.jsx
// account-switcher.jsx — React port of ui-shared-solid/AccountSwitcher.tsx.
//
// Selects the active Anthropic account for new requests. Renders only when
// at least one kind==="anthropic" account is known (nothing to pick before
// the server has sent its account list) — this mirrors the Solid original's
// early `return null`, ported as a guard clause instead of an early
// component return (React components must always return via JSX, but an
// empty render reads the same to the caller).
//
// The leading "— Auto —" option (value="") reverts to broker rotation (a
// null selectedId). Unhealthy accounts are shown but disabled so the user
// can see they exist without being able to select a dead account.
import React from "react";

export function AccountSwitcher({ accounts, selectedId, onSelect, disabled }) {
  const anthropicAccounts = (accounts || []).filter((a) => a.kind === "anthropic");
  if (anthropicAccounts.length === 0) return null;

  return (
    <select
      className="stg-field-input"
      value={selectedId ?? ""}
      disabled={disabled}
      onChange={(e) => {
        const val = e.target.value;
        onSelect(val === "" ? null : val);
      }}
      style={{ fontSize: "inherit" }}
    >
      <option value="">— Auto —</option>
      {anthropicAccounts.map((acct) => (
        <option key={acct.id} value={acct.id} disabled={acct.health !== "healthy"}>
          {acct.label}
          {acct.health !== "healthy" ? " (unavailable)" : ""}
        </option>
      ))}
    </select>
  );
}
