// packages/ui-shared-solid/src/ObsPanel.tsx
/**
 * ObsPanel (Solid) — observability pane: kind chips, drop banner,
 * meta line, and the streaming event log.
 *
 * Solid port of apps/ui-web/src/App.tsx ObsPanel (~line 965).
 *
 * Stays a "presentation" component — all filter state (selectedKinds,
 * etc.) lives in the owning App so the chip-set + transcript share
 * the same store. Same prop shape as React for behavior parity.
 */
import { type Component, For, Show } from "solid-js"
import type { ObsEvent } from "@luna/ui-shared/core"
import { EventRow } from "./EventRow.jsx"

export interface ObsPanelProps {
  readonly allKinds: ReadonlyArray<string>
  readonly selectedKinds: ReadonlySet<string>
  readonly toggleKind: (k: string) => void
  readonly clearKinds: () => void
  readonly filtered: ReadonlyArray<ObsEvent>
  readonly totalEvents: number
  readonly lastDrop: { readonly n: number; readonly since: string } | null
  readonly droppedTotal: number
  readonly lastPingAt: string | null
}

export const ObsPanel: Component<ObsPanelProps> = (props) => {
  return (
    <>
      <div class="topbar" style={{ "border-top": "1px solid #222" }}>
        <div class="row chips">
          <Show when={props.allKinds.length === 0}>
            <span class="muted">no kinds yet — connect to see events</span>
          </Show>
          <For each={props.allKinds}>
            {(k) => (
              <button
                class={`chip ${props.selectedKinds.has(k) ? "active" : ""}`}
                onClick={() => props.toggleKind(k)}
              >
                {k}
              </button>
            )}
          </For>
          <Show when={props.selectedKinds.size > 0}>
            <button class="chip clear" onClick={() => props.clearKinds()}>
              clear
            </button>
          </Show>
        </div>
        <Show when={props.lastDrop}>
          {(drop) => (
            <div class="banner drop">
              ⚠ dropped {props.droppedTotal} event(s) total · most recent
              burst: {drop().n} since {drop().since}
            </div>
          )}
        </Show>
      </div>
      <main class="log">
        <div class="meta">
          {props.filtered.length} / {props.totalEvents} event(s) shown
          <Show when={props.lastPingAt}>
            <span class="muted"> · last ping {props.lastPingAt}</span>
          </Show>
        </div>
        <For each={props.filtered}>
          {(ev) => <EventRow event={ev} />}
        </For>
      </main>
    </>
  )
}

// apps/ui-web/src/studio/obs-panel.jsx
// obs-panel.jsx — Luna Studio observability panel: kind chips, drop banner,
// meta line, and the streaming event log.
//
// React port of packages/ui-shared-solid/src/{ObsPanel,EventRow}.tsx (which
// themselves ported the original apps/ui-web/src/App.tsx ObsPanel/EventRow +
// filter-state wiring at App.tsx L406-421: allKinds/filtered/toggleKind).
//
// Unlike the Solid version (which took selectedKinds/toggleKind/clearKinds as
// props from the owning App), this panel OWNS its filter state: Studio's
// final-app has no parent store for it, so selectedKinds lives here as a
// plain useState<Set<string>>. Everything else — data in, no frames out — is
// a pure client-side view over ctx.state; it renders empty until connected
// and needs no capability gate.
import React, { useCallback, useMemo, useState } from "react";
import { filterEvents, formatVal } from "@luna/ui-shared/core";

// Defense-in-depth: ObsEvent's `[key: string]: unknown` index signature means
// a future event kind could carry a credential-shaped field. Nothing in the
// current wire shape does, but per project rule ("never render secret
// values") we redact anything that *looks* like one before it ever reaches
// JSON.stringify or the summary preview, rather than trusting the server.
const SECRET_KEY_RE = /token|secret|password|passwd|authoriz|api[-_]?key|credential/i;
const REDACTED = "••••";

function redactSecrets(value) {
  if (Array.isArray(value)) return value.map(redactSecrets);
  if (value && typeof value === "object") {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      out[k] = SECRET_KEY_RE.test(k) ? REDACTED : redactSecrets(v);
    }
    return out;
  }
  return value;
}

/**
 * Single ObsEvent row in the event log. Click toggles a JSON-formatted
 * detail view. Summary line previews up to three non-meta keys via
 * formatVal, same as the Solid original.
 */
export function EventRow({ event }) {
  const [open, setOpen] = useState(false);

  const summary = useMemo(() => {
    const { ts, kind, level, ...rest } = event;
    void ts;
    void kind;
    void level;
    const keys = Object.keys(rest).slice(0, 3);
    const preview = keys
      .map((k) => `${k}=${formatVal(SECRET_KEY_RE.test(k) ? REDACTED : rest[k])}`)
      .join(" ");
    return preview || event.kind;
  }, [event]);

  return (
    <div
      className={`obs-row-event level-${event.level}`}
      onClick={() => setOpen((o) => !o)}
    >
      <span className="obs-ts">{event.ts.slice(11, 23)}</span>
      <span className={`obs-kind kind-${event.kind}`}>{event.kind}</span>
      <span className="obs-summary">{summary}</span>
      {open && (
        <pre className="obs-json">
          {JSON.stringify(redactSecrets(event), null, 2)}
        </pre>
      )}
    </div>
  );
}

/**
 * ObsPanel — kind chips, drop banner, meta line, and the event log.
 *
 * Props are plain data read off ctx.state (see integration spec); this
 * component computes allKinds/filtered/toggleKind/clearKinds itself instead
 * of receiving them, since Studio has no parent store to hold them.
 */
export function ObsPanel({
  events,
  seenKinds,
  advertisedKinds,
  lastDrop,
  droppedTotal,
  lastPingAt,
}) {
  const [selectedKinds, setSelectedKinds] = useState(() => new Set());

  const allKinds = useMemo(() => {
    const set = new Set(advertisedKinds || []);
    for (const k of seenKinds || []) set.add(k);
    return Array.from(set).sort();
  }, [advertisedKinds, seenKinds]);

  const filtered = useMemo(
    () => filterEvents(events || [], selectedKinds),
    [events, selectedKinds],
  );

  const toggleKind = useCallback((k) => {
    setSelectedKinds((prev) => {
      const next = new Set(prev);
      if (next.has(k)) next.delete(k);
      else next.add(k);
      return next;
    });
  }, []);

  const clearKinds = useCallback(() => setSelectedKinds(new Set()), []);

  const totalEvents = (events || []).length;

  return (
    <div className="obs-panel">
      <div className="obs-topbar">
        <div className="obs-row obs-chips">
          {allKinds.length === 0 && (
            <span className="obs-muted">no kinds yet — connect to see events</span>
          )}
          {allKinds.map((k) => (
            <button
              key={k}
              className={`obs-chip${selectedKinds.has(k) ? " active" : ""}`}
              onClick={() => toggleKind(k)}
            >
              {k}
            </button>
          ))}
          {selectedKinds.size > 0 && (
            <button className="obs-chip clear" onClick={clearKinds}>
              clear
            </button>
          )}
        </div>
        {lastDrop && (
          <div className="obs-banner drop">
            ⚠ dropped {droppedTotal} event(s) total · most recent burst: {lastDrop.n}{" "}
            since {lastDrop.since}
          </div>
        )}
      </div>
      <main className="obs-log">
        <div className="obs-meta">
          {filtered.length} / {totalEvents} event(s) shown
          {lastPingAt && <span className="obs-muted"> · last ping {lastPingAt}</span>}
        </div>
        {filtered.map((ev, i) => (
          <EventRow key={`${ev.ts}_${ev.kind}_${i}`} event={ev} />
        ))}
      </main>
    </div>
  );
}

export default ObsPanel;
